#!/usr/bin/env bash

set -e

TYPE="release"
HOST="cftest.wwwtech.de"
WITH=""

while getopts ":h:t:w:" opt; do
  case $opt in
    h)
      HOST=$OPTARG
      ;;
    t)
      TYPE=$OPTARG

      if [[ $TYPE == "upgrade" ]]; then
        WITH=$(ls .deliver/releases | sed 's/cforum_//' | sed -e 's/\.release\.tar\.gz//; s/\.upgrade\.tar\.gz//' | sort -V | tail -1)
      fi
      ;;
    w)
      WITH=$OPTARG
      ;;
  esac
done

if [[ $TYPE == "release" ]]; then
  echo "building $TYPE for $HOST"
else
  echo "building $TYPE for $HOST with $WITH"
fi

name=cforum-elixir-build

result=$(docker images -q $name 2> /dev/null)

if [[ -z "$result" ]]; then
  docker build --tag=$name -f rel/Dockerfile .
fi

result=$(docker images -q $name)

if [[ -n "$result" ]]; then
  [[ $(docker ps -f "name=$name" --format '{{.Names}}') == $name ]] || docker start $name
else
  docker run -d -p 23:22 -P --name $name $name
fi

scp .deliver/secrets/prod.$HOST.exs builder@builder:~/config/prod.exs
scp config/appsignal.exs builder@builder:~/config

if [[ $TYPE == "release" ]]; then
  mix edeliver build $TYPE
else
  mix edeliver build $TYPE --with=$WITH
fi

docker container stop $name
